openapi: 3.0.0
info:
  title: Регистрация пользователя API
  description: API для регистрации новых пользователей
  version: 1.0.0
servers:
  - url: http://example.com/api
paths:
  /signUp:
    post:
      summary: Регистрация нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  description: Имя пользователя
                email:
                  type: string
                  format: email
                  description: Адрес электронной почты пользователя
                password:
                  type: string
                  format: password
                  description: Пароль пользователя
                confirmPassword:
                  type: string
                  format: password
                  description: Подтверждение пароля пользователя
      responses:
        "200":
          description: Успешная регистрация
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Сообщение об успешной регистрации
        "400":
          description: Некорректные данные в запросе
        "404":
          description: Запрашиваемый маршрут не найден
        "405":
          description: Метод не разрешен
        "500":
          description: Внутренняя ошибка сервера
